language: python
python:
  - "3.9-dev"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
matrix:
  allow_failures:
    - python: "3.9-dev"
before_install:
  - pip install -U pip setuptools
  - pip install git+https://github.com/PeterJCLaw/srcomp.git
  - pip install -r script/linting/requirements.txt
install: pip install .
script: script/linting/lint
